spring.application.name=taco-cloud
spring.datasource.generate-unique-name=false
spring.datasource.name=tacocloud
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml


#??????????? ? Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/tacocloud
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

logging.level.liquibase=DEBUG

spring.jpa.show-sql=true